all: generate
.PHONY: all

.PHONY: generate_1_to_7
generate_1_to_7:
	sh generate.sh 7

.PHONY: generate_8
.PHONY: generated/ps_hardcoded_tst_8.c.txt generated/ps_hardcoded_tsb_8.c.txt generated/ps_hardcoded_txt_8.c.txt generated/ps_hardcoded_txb_8.c.txt generated/ps_hardcoded_tot_8.c.txt generated/ps_hardcoded_tos_8.c.txt generated/ps_hardcoded_tob_8.c.txt generated/ps_hardcoded_sss_8.c.txt generated/ps_hardcoded_sxs_8.c.txt generated/ps_hardcoded_sot_8.c.txt generated/ps_hardcoded_sos_8.c.txt generated/ps_hardcoded_sob_8.c.txt generated/ps_hardcoded_bst_8.c.txt generated/ps_hardcoded_bsb_8.c.txt generated/ps_hardcoded_bxt_8.c.txt generated/ps_hardcoded_bxb_8.c.txt generated/ps_hardcoded_bot_8.c.txt generated/ps_hardcoded_bos_8.c.txt generated/ps_hardcoded_bob_8.c.txt
generate_8: generated/ps_hardcoded_tst_8.c.txt generated/ps_hardcoded_tsb_8.c.txt generated/ps_hardcoded_txt_8.c.txt generated/ps_hardcoded_txb_8.c.txt generated/ps_hardcoded_tot_8.c.txt generated/ps_hardcoded_tos_8.c.txt generated/ps_hardcoded_tob_8.c.txt generated/ps_hardcoded_sss_8.c.txt generated/ps_hardcoded_sxs_8.c.txt generated/ps_hardcoded_sot_8.c.txt generated/ps_hardcoded_sos_8.c.txt generated/ps_hardcoded_sob_8.c.txt generated/ps_hardcoded_bst_8.c.txt generated/ps_hardcoded_bsb_8.c.txt generated/ps_hardcoded_bxt_8.c.txt generated/ps_hardcoded_bxb_8.c.txt generated/ps_hardcoded_bot_8.c.txt generated/ps_hardcoded_bos_8.c.txt generated/ps_hardcoded_bob_8.c.txt
generated/ps_hardcoded_tst_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_tst 8 tst > generated/ps_hardcoded_tst_8.c.txt
generated/ps_hardcoded_tsb_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_tsb 8 tsb > generated/ps_hardcoded_tsb_8.c.txt
generated/ps_hardcoded_txt_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_txt 8 txt > generated/ps_hardcoded_txt_8.c.txt
generated/ps_hardcoded_txb_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_txb 8 txb > generated/ps_hardcoded_txb_8.c.txt
generated/ps_hardcoded_tot_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_tot 8 tot > generated/ps_hardcoded_tot_8.c.txt
generated/ps_hardcoded_tos_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_tos 8 tos > generated/ps_hardcoded_tos_8.c.txt
generated/ps_hardcoded_tob_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_tob 8 tob > generated/ps_hardcoded_tob_8.c.txt
generated/ps_hardcoded_sss_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_sss 8 sss > generated/ps_hardcoded_sss_8.c.txt
generated/ps_hardcoded_sxs_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_sxs 8 sxs > generated/ps_hardcoded_sxs_8.c.txt
generated/ps_hardcoded_sot_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_sot 8 sot > generated/ps_hardcoded_sot_8.c.txt
generated/ps_hardcoded_sos_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_sos 8 sos > generated/ps_hardcoded_sos_8.c.txt
generated/ps_hardcoded_sob_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_sob 8 sob > generated/ps_hardcoded_sob_8.c.txt
generated/ps_hardcoded_bst_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_bst 8 bst > generated/ps_hardcoded_bst_8.c.txt
generated/ps_hardcoded_bsb_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_bsb 8 bsb > generated/ps_hardcoded_bsb_8.c.txt
generated/ps_hardcoded_bxt_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_bxt 8 bxt > generated/ps_hardcoded_bxt_8.c.txt
generated/ps_hardcoded_bxb_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_bxb 8 bxb > generated/ps_hardcoded_bxb_8.c.txt
generated/ps_hardcoded_bot_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_bot 8 bot > generated/ps_hardcoded_bot_8.c.txt
generated/ps_hardcoded_bos_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_bos 8 bos > generated/ps_hardcoded_bos_8.c.txt
generated/ps_hardcoded_bob_8.c.txt:
	node --max_old_space_size=4096 dist/index.js ps_hardcoded_bob 8 bob > generated/ps_hardcoded_bob_8.c.txt

.PHONY: generated/ps_hardcoded_sxs_9.c.txt
generated/ps_hardcoded_sxs_9.c.txt:
	node --max_old_space_size=8192 dist/index.js ps_hardcoded_sxs 9 sxs > generated/ps_hardcoded_sxs_9.c.txt
.PHONY: generated/ps_hardcoded_txt_9.c.txt
generated/ps_hardcoded_txt_9.c.txt:
	node --max_old_space_size=8192 dist/index.js ps_hardcoded_txt 9 txt > generated/ps_hardcoded_txt_9.c.txt
.PHONY: generated/ps_hardcoded_txb_9.c.txt
generated/ps_hardcoded_txb_9.c.txt:
	node --max_old_space_size=8192 dist/index.js ps_hardcoded_txb 9 txb > generated/ps_hardcoded_txb_9.c.txt
.PHONY: generated/ps_hardcoded_bxt_9.c.txt
generated/ps_hardcoded_bxt_9.c.txt:
	node --max_old_space_size=8192 dist/index.js ps_hardcoded_bxt 9 bxt > generated/ps_hardcoded_bxt_9.c.txt
.PHONY: generated/ps_hardcoded_bxb_9.c.txt
generated/ps_hardcoded_bxb_9.c.txt:
	node --max_old_space_size=8192 dist/index.js ps_hardcoded_bxb 9 bxb > generated/ps_hardcoded_bxb_9.c.txt

.PHONY: generate
generate: generate_1_to_7 generate_8
